language: node_js
node_js:
- '6'
- '7'
- '8'
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: d6rpnGwsHWJ04uwPJCVkmYXaJT3NfyWdNxWw/676jwqmor7+uupt4qntvVrHX9Ky8vwaw6HKd7ThM8avDCs+fF7GvVgGPu6yOvzFeTm2qQTnFsW7IqSahx3gl77lAm2A7oKUJ45qCNxFcdJexurBMEiaC7FZxUkhF5bBXrWS0cUlT1vPijiHpZOL5IbsZVmR2AJLuB6lpsY8etUW9qmT/Jg6FLcmZBWrgetfRdS2KmFrXbKjnP+9ycFHRln9qlftaxhmRIwYJKnLpeQbB9SG1g2P5CaFzNX/2nQHOg/0XRMJDSjo9HFZ4dGp4mWbsM0bcPIopxenlHe4mOOmgdrnaIPgmWq8jiVrF4F+g5yBwaj1oBnCu4hvj4hXQEbFyd/rwDIjLtZMnVk7Gy5X1MAKicwzvBBL+2spzz9Bccn5bKxe4vWh/utPG1Ibn0Qn7vafLaz7DTM56aL9P1hXOx2QJ6S5rqa/melOMSmoCHeL9K2WV4MC8vCCauLrEER8+QE2Ayh7AgNS7I5Vicc86j/W8A1Td1IVoie9VHsZo/9H1nwdnUXpQ2VrrmZopYNRwWkccsXPRruk49p4JT9cCRvfMGNt6O358iUE0xzju37YW8BztJs4IUivSBQ1LVMykq2plxjLEJ/hCJnOBH0X7AHo/+uTbXgLHqXLiFLeaQEpOF4=
  on:
    tags: true
    repo: jaumard/trailpack-email
    all_branches: true
    node: 7
