language: node_js
node_js:
- '6'
- '7'
- '8'
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: XpVElUpyXf9ID5mNZMNLz52eB63OJQDcmt8RlvRiZKws65ZQPyObHa5sQz093zFi8Oi4CTcuvft0JlwINdDz5jUm3mB2OgWYWomdONIa6xHwj40H5PDy82kmwToK+MA4aXP2L4H5eTRXF3MFccN1x0/96noSlwvaAEBnH/IXU0T6tQa8aKfy21Cl43sEbjm4kNTm+yIGGHbbokWyQ+VtMy8IHX1v07bcfD3ynPGgH8tbys+4BPM7hBn2V8ZOtjmDrI9GV4r6+y7xWdPnY45CGN9gGIrZ2z2H88roR2FFrbkzEM9Ik/8YbkKYfCgdHd34O8CvfglWZQcH0DHNQR+n2yiQH+aNEXn79cizb+RfuhIfRXr5oostyziypYDLi45HHUkWlLNaS4sRWFeZNVE9kiTPSVmgMVq+zrM3840W7Lnv7XSW6S0SbUm7krbeVFGTRiBnz8akh3tp9oduhbaaShOdKJ4lBtms1tzFXLKLi1+vNKVUTso25jFKgDvwkVwgUpFstfmlpOE5oNoI35YYI8A4Jii0NnLmr2Pz5SyljWcAxkVazrw+IGfwgykGrt7W4b2GZpqw4qpAN3xC6+XcN+uPJz4G+I5zbrkEt3olA6nbHwv8tJZzn18xy/gIpdAo6sL7JH4kILsmd2i2OkWOQEMCgT6MAezYFGoofKhOTTQ=
  on:
    tags: true
    repo: jaumard/trailpack-email
    all_branches: true
    node: 7
