language: node_js
node_js:
- '8'
- '9'
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: bB9KABPqghWfFqdCwefFFRsf3NanGt3E5RjgWJu5mf4a1pg3bIYYBiSNOxpnyn6SUiTKDBb1uWKB3R78g9v1ps3y1uDo/LbY8Wc8BIil1rxoTZFinvtPuSzU83seJDdIK2bM8S/Ykl85bgt7WMIOQU6/OAY/G7CXjhUTe4OnePB8I0MaKdAzOxVclFsG8GYNSPBCatAd7gSZlPxCZpyDkLgss5Rlpf2W0VMqWt4XrQpj/BlHjk7KNEcsdPRu7K0xQX7lrbLuJiiRS0c/4HnFuNwiABssyBsL+ZnPm6I55L2y6nIvq614I6PDPV056eFzHZNv3936AgzXaZ6aklQbBwBxK7NWuO3y4fGYLGKg6gqKaLohT8PaKdL5jFEOnacWGHYj/HR85xVlmUcgkqV0LloPEahx6OaU/lkdImYVM1GVYw6XkWB5c6BG3lxRIevraJ01KfcporyW2csiQOMVzrn4+0aFxbPUGcFPE8+qUXvUo0Cbb6Q9pKVtJXIQXo5VrUz+/hHadDftnYyHTt9a6ycCN2NHzFG7UAvZfAtjjb9tFYmWBZPuSTbNCWbqKzhuHSr2fFOs42O2/l/gBgkJRc/JMnKzEUo9+OpCj5MXPtF2qwRMT69du2Ri5iFbaVTKE2WS1UPJZg9Myun8OiE52fO2WlzyqEk/B0Kb1v4l8G0=
  on:
    tags: true
    repo: jaumard/trailpack-email
    all_branches: true
    node: 8
